### ISSUE TITLE
yarn bridge-init <nRF Cloud api key> give errors report

### ISSUE THREAD

**Issue by charlieshao5189** [nRFCloud/mqtt-bridge-mosquitto#1]
Originally report by case: https://devzone.nordicsemi.com/f/nordic-q-a/86063/mqtt-bridge-mosquitto-cannot-find-module

https://docs.nrfcloud.com/Guides/Messages/SetupMessageBridge/#steps 
Run Step3 gives errors:

**
yarn bridge-init a6a0d3f0fc4fd3b61ab47366772xxxxxxxxxxxxxxxxxxxxxx
yarn run v1.22.18
$ node dist/scripts/init.js a6a0d3f0fc4fd3b61ab47366772a7d89eca8e439
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/charlie/Development/MQTT-bridge-mosquitto/dist/scripts/init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
**

**Comment by jfrconley** [comment]
Looks like there's a missing step to run `yarn compile` after `yarn install`. I'll work on updating the Readme, will move constructs to v2 as well to avoid the peer dep warnings.
